import React from 'react';
import Navbar from '../components/Navbar';

const About = () => {
  return (
    <div className="min-h-screen bg-[#020617] text-white">
      <Navbar />
      
      <div className="pt-24 pb-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold lex-gradient-text mb-4">
              About the Project
            </h1>
            <p className="text-xl text-gray-300 max-w-2xl mx-auto">
              AI-Driven Research Engine for Commercial Courts
            </p>
          </div>

          <div className="space-y-8">
            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10">
              <p className="text-lg text-gray-300 leading-relaxed">
                AI-Driven Research Engine for Commercial Courts is a web-based application developed to assist in legal research by using Artificial Intelligence techniques. The system helps users quickly find relevant case laws, legal provisions, and summaries based on their queries.
              </p>
              <br />
              <p className="text-lg text-gray-300 leading-relaxed">
                This project aims to demonstrate how AI can simplify and speed up the legal research process by retrieving similar cases (precedents), extracting key legal information, and presenting results in a structured and user-friendly manner.
              </p>
            </div>

            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10">
              <h2 className="text-2xl font-bold text-lex-gold mb-4">Objective</h2>
              <p className="text-lg text-gray-300 mb-4">
                The objective of this project is to:
              </p>
              <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
                <li>Reduce the time required for legal research</li>
                <li>Provide relevant case laws and legal references</li>
                <li>Demonstrate the use of AI in the legal domain</li>
              </ul>
            </div>

            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10">
              <h2 className="text-2xl font-bold text-lex-gold mb-4">Developed By</h2>
              <div className="text-center">
                <p className="text-lg text-white font-semibold">Riya Sajnani</p>
                <p className="text-lg text-white font-semibold">Sameer More</p>
                <p className="text-lg text-white font-semibold">Sandeep Mewada</p>
                <p className="text-sm text-gray-400 mt-2">
                  (B.Tech Computer Science Engineering Students)
                </p>
              </div>
            </div>

            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10">
              <h2 className="text-2xl font-bold text-lex-gold mb-4">Technologies Used</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-blue-500 rounded-full"></div>
                  <span className="text-gray-300">React.js (Frontend)</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-green-500 rounded-full"></div>
                  <span className="text-gray-300">Node.js & Express (Backend)</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-purple-500 rounded-full"></div>
                  <span className="text-gray-300">Gemini API (AI Processing)</span>
                </div>
                <div className="flex items-center space-x-3">
                  <div className="w-3 h-3 bg-green-600 rounded-full"></div>
                  <span className="text-gray-300">MongoDB (Database)</span>
                </div>
              </div>
            </div>

            <div className="bg-red-500/10 backdrop-blur-sm rounded-xl p-8 border border-red-500/20">
              <h2 className="text-2xl font-bold text-red-400 mb-4">Disclaimer</h2>
              <p className="text-gray-300 leading-relaxed">
                This project is developed for educational purposes only.
                The system acts as a research assistant and does not provide legal advice or make judicial decisions. All results generated by the system are for demonstration and learning purposes only.
              </p>
            </div>

            <div className="bg-white/5 backdrop-blur-sm rounded-xl p-8 border border-white/10">
              <h2 className="text-2xl font-bold text-lex-gold mb-4">Future Scope</h2>
              <ul className="list-disc list-inside text-gray-300 space-y-2 ml-4">
                <li>Support for multiple languages</li>
                <li>Advanced legal prediction models</li>
                <li>Integration with larger legal datasets</li>
                <li>Improved accuracy of AI-based search</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;